export const USER_MOCK : any = {

    login : [{
        bestTimeToCall          : '6am - 10am',
        city                    : 'Chattanooga',
        companyName             : 'UNUM',
        contactPreference       : [
            'Text',
            'Email'
        ],
        DOB                     : '11/26/1982',
        email                   : 'stacy.gray@unum.com',
        employeeId              : '00D220000004XxbEAE',
        firstName               : 'Stacy',
        gender                  : 'Female',
        id                      : '00D220000004XxbEAF',
        isActive                : true,
        lastName                : 'Gray',
        language                : 'English',
        middleName              : 'J',
        mobilePhone             : '615-789-9976',
        name                    : 'Stacy Gray',
        phone                   : '615-789-9976',
        phoneType               : 'Cell',
        postalCode              : 37402,
        SSN                     : '411-56-7893',
        state                   : 'TN',
        street                  : '1 Fountain Square',
        timeZone                : 'America/New_York',
        title                   : 'Mrs',
        username                : 'Stacy Gray',
        userType                : 'Standard'
    }],
    loginWrap : {
        bestTimeToCall          : '6am - 10am',
        city                    : 'Chattanooga',
        companyName             : 'UNUM',
        contactPreference       : [
            'Text',
            'Email'
        ],
        DOB                     : '11/26/1982',
        email                   : 'stacy.gray@unum.com',
        employeeId              : '00D220000004XxbEAE',
        firstName               : 'Stacy',
        gender                  : 'Female',
        id                      : '00D220000004XxbEAF',
        isActive                : true,
        lastName                : 'Gray',
        language                : 'English',
        middleName              : 'J',
        mobilePhone             : '615-789-9976',
        name                    : 'Stacy Gray',
        phone                   : '615-789-9976',
        phoneType               : 'Cell',
        postalCode              : 37402,
        SSN                     : '411-56-7893',
        state                   : 'TN',
        street                  : '1 Fountain Square',
        timeZone                : 'America/New_York',
        title                   : 'Mrs',
        username                : 'Stacy Gray',
        userType                : 'Standard'
    },

    logout : [],
    logoutWrap : {},

    getCurrentUser : [{
        bestTimeToCall          : '6am - 10am',
        city                    : 'Chattanooga',
        companyName             : 'UNUM',
        contactPreference       : [
            'Text',
            'Email'
        ],
        DOB                     : '11/26/1982',
        email                   : 'stacy.gray@unum.com',
        employeeId              : '00D220000004XxbEAE',
        firstName               : 'Stacy',
        gender                  : 'Female',
        id                      : '00D220000004XxbEAF',
        isActive                : true,
        lastName                : 'Gray',
        language                : 'English',
        middleName              : 'J',
        mobilePhone             : '615-789-9976',
        name                    : 'Stacy Gray',
        phone                   : '615-789-9976',
        phoneType               : 'Cell',
        postalCode              : 37402,
        SSN                     : '411-56-7893',
        state                   : 'TN',
        street                  : '1 Fountain Square',
        timeZone                : 'America/New_York',
        title                   : 'Mrs',
        username                : 'Stacy Gray',
        userType                : 'Standard'
    }],
    getCurrentUserWrap : {
        bestTimeToCall          : '6am - 10am',
        city                    : 'Chattanooga',
        companyName             : 'UNUM',
        contactPreference       : [
            'Text',
            'Email'
        ],
        DOB                     : '11/26/1982',
        email                   : 'stacy.gray@unum.com',
        employeeId              : '00D220000004XxbEAE',
        firstName               : 'Stacy',
        gender                  : 'Female',
        id                      : '00D220000004XxbEAF',
        isActive                : true,
        lastName                : 'Gray',
        language                : 'English',
        middleName              : 'J',
        mobilePhone             : '615-789-9976',
        name                    : 'Stacy Gray',
        phone                   : '615-789-9976',
        phoneType               : 'Cell',
        postalCode              : 37402,
        SSN                     : '411-56-7893',
        state                   : 'TN',
        street                  : '1 Fountain Square',
        timeZone                : 'America/New_York',
        title                   : 'Mrs',
        username                : 'Stacy Gray',
        userType                : 'Standard'
    },

    resetPassword : [],
    resetPasswordWrap : {},

    updateUser : [],
    updateUserWrap : {}
};
